version: '3.8'

services:
  app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8087:8080"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./BDD.sql:/docker-entrypoint-initdb.d/BDD.sql
    env_file:
      - .env
    ports:
      - "3306:3306"

volumes:
  db_data:
