version: '3'

services:

  database:
    image: mysql:8.0.33
    volumes:
      - db_data:/var/lib/mysql
      - ./BDD.sql:/docker-entrypoint-initdb.d/BDD.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=projetgo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

volumes:
  db_data:
